name: nice

on:
  workflow_dispatch:
    inputs:
      benchmark_path:
        description: 'Path to the benchmark'
        required: true
        default: 'actions.yml'
    
jobs:
  ancd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: dipankardas011/niceni/${{ inputs.benchmark_path }}@main
